name: Run Trading Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (UTC)
  workflow_dispatch:        # Allows manual run from GitHub UI

jobs:
  run-trading-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading script
        run: python main.py
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          N8N_UPDATE_WEBHOOK_URL: ${{ secrets.N8N_UPDATE_WEBHOOK_URL }}

      - name: Commit updated trades.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "bot@example.com"
          git pull origin main || true
          git add trades.json
          git diff --cached --quiet || git commit -m "Update trades.json on $(date)"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main

